name = "burnfolio"
main = "dist/worker/index.js"
compatibility_date = "2026-06-21"
workers_dev = true
routes = [
  { pattern = "burnfolio.ai", custom_domain = true }
]

[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "burnfolio"
database_id = "438436b3-8410-4a91-b3bc-ec32e0610d27"

[[send_email]]
name = "EMAIL"
remote = true
